README.md, ncds-sdk/src/main/java/com/nasdaq/ncdsclient/consumer/NasdaqKafkaAvroConsumer.java, ncds-sdk/src/main/java/com/nasdaq/ncdsclient/internal/ReadSchemaTopic.java, ncdssdk-client/src/main/java/com/nasdaq/ncdsclient/NCDSSession.java
=> adding latest offset

README.md, docker/Dockerfile, docker/README.md, docker/auth.properties, docker/kafka.properties, docker/run-sdk-app.sh, ncds-sdk/src/main/java/com/nasdaq/ncdsclient/internal/utils/AuthenticationConfigLoader.java, ncdssdk-client/src/main/java/com/nasdaq/ncdsclient/NCDSSession.java
Adding docker files and documentation for SDK
=> Docker sdk

ncds-sdk/src/main/java/com/nasdaq/ncdsclient/internal/utils/AuthenticationConfigLoader.java
Reading client-id for docker from the environment variable
=> Client-id for docker

docker/mirrormaker/README.md, docker/mirrormaker/consumer.properties, docker/mirrormaker/producer.properties, docker/mirrormaker/run-mirror-maker.sh, docker/run-sdk-app.sh
Nasdaq Cloud Data Service - Kafka mirroring with MirrorMaker
=> Adding mirror-maker

docker/mirrormaker/README.md, docker/mirrormaker/template/install_mirror_maker.sh, docker/mirrormaker/template/kafka-mirror-maker.yaml
Adding mirror-maker helm template
=> Adding mirror-maker helm template

docker/README.md, docker/mirrormaker/README.md
Updating mirror-maker documentation
=> Updating mirror-maker documentation

README.md, ncds-sdk/src/main/java/com/nasdaq/ncdsclient/NCDSClient.java, ncds-sdk/src/main/java/com/nasdaq/ncdsclient/consumer/NasdaqKafkaAvroConsumer.java, ncds-sdk/src/main/java/com/nasdaq/ncdsclient/news/News.java, ncds-sdk/src/main/java/com/nasdaq/ncdsclient/news/NewsUtil.java, ncds-sdk/src/main/resources/NewsSchema.avsc, ncdssdk-client/src/main/java/com/nasdaq/ncdsclient/NCDSSession.java
Adding the method to get KafkaConsumer to read  news in Avro message format
=> Adding news reader in SDK

.gitattributes, README.md, ncds-sdk/src/main/java/com/nasdaq/ncdsclient/NCDSClient.java, ncds-sdk/src/main/java/com/nasdaq/ncdsclient/consumer/NasdaqKafkaAvroConsumer.java, ncdssdk-client/src/main/java/com/nasdaq/ncdsclient/NCDSSession.java
Adding topic selection for news
=> Adding topic selection for news

README.md
=> Adding Datasets list

ncds-sdk/src/main/java/com/nasdaq/ncdsclient/internal/ReadSchemaTopic.java, ncds-sdk/src/main/resources/schemas/CTA-A-UF30.avsc, ncds-sdk/src/main/resources/schemas/CTA-B-UF30.avsc, ncds-sdk/src/main/resources/schemas/GIDS.avsc, ncds-sdk/src/main/resources/schemas/MOCK.avsc, ncds-sdk/src/main/resources/schemas/NLSCTA.avsc, ncds-sdk/src/main/resources/schemas/NLSUTP.avsc, ncds-sdk/src/main/resources/schemas/QBBO-A-BSX.avsc, ncds-sdk/src/main/resources/schemas/QBBO-A-CORE.avsc, ncds-sdk/src/main/resources/schemas/QBBO-A-PSX.avsc, ncds-sdk/src/main/resources/schemas/QBBO-B-BSX.avsc, ncds-sdk/src/main/resources/schemas/QBBO-B-CORE.avsc, ncds-sdk/src/main/resources/schemas/QBBO-B-PSX.avsc, ncds-sdk/src/main/resources/schemas/QBBO-C-BSX.avsc, ncds-sdk/src/main/resources/schemas/QBBO-C-CORE.avsc, ncds-sdk/src/main/resources/schemas/QBBO-C-PSX.avsc, ncds-sdk/src/main/resources/schemas/TOTALVIEW-BSX.avsc, ncds-sdk/src/main/resources/schemas/TOTALVIEW-PSX.avsc, ncds-sdk/src/main/resources/schemas/TOTALVIEW.avsc, ncds-sdk/src/main/resources/schemas/UTPBIN-UF30.avsc
=> Schema-fallback

README.md, ncds-sdk/src/main/java/com/nasdaq/ncdsclient/NCDSClient.java, ncds-sdk/src/main/java/com/nasdaq/ncdsclient/consumer/NasdaqKafkaAvroConsumer.java, ncdssdk-client/src/main/java/com/nasdaq/ncdsclient/NCDSSession.java
As a user, if my conenction drops, I want to connect to an entitled topic and playback from a certain time (eg. my connection dropped at 10AM, so i want to connect to Basic at 959AM and resume stream).
=> Connect to kafka topic and playback from a specific time

README.md, ncds-sdk/pom.xml, ncds-sdk/src/main/java/com/nasdaq/ncdsclient/NCDSClient.java, ncds-sdk/src/main/java/com/nasdaq/ncdsclient/internal/ReadSchemaTopic.java, ncds-sdk/src/main/java/com/nasdaq/ncdsclient/internal/utils/AuthenticationConfigLoader.java, ncdssdk-client/pom.xml, ncdssdk-client/src/main/java/com/nasdaq/ncdsclient/NCDSSession.java, ncdssdk-client/src/main/resources/clientAuthentication-config.properties, pom.xml
1. Filter Stream - Filtering the symbols and message types
2. Get all messages - Get all messages for given message types
3. Updating Documentation
4. Removing oauth.username.claim from config
=> FilterStream + get all messages + updating documentation

ncdssdk-client/src/main/resources/clientAuthentication-config.properties, ncdssdk-client/src/main/resources/kafka-config.properties
=> Adding properties files

docker/Dockerfile, docker/mirrormaker/template/kafka-mirror-maker.yaml, ncds-sdk/pom.xml, ncds-sdk/src/main/java/com/nasdaq/ncdsclient/consumer/NasdaqKafkaAvroConsumer.java, ncds-sdk/src/main/java/com/nasdaq/ncdsclient/internal/utils/InstallCertificates.java, ncds-sdk/src/test/java/com/nasdaq/ncdsclient/NCDSSDKJunitTest.java, ncds-sdk/src/test/java/com/nasdaq/ncdsclient/utils/AvroMocker.java, ncds-sdk/src/test/java/com/nasdaq/ncdsclient/utils/NCDSTestUtil.java, ncds-sdk/src/test/java/com/nasdaq/ncdsclient/utils/PlainListenerSpecificPort.java, ncdssdk-client/pom.xml, pom.xml
Updating SDK to use Kafka 2.6.0
Updating base docker image for 0.20.0
Updating mirrormaker
Updating certificate management code to download the correct cert
Adding date in consumer-group-id
=> SDK 0.3.0 release

ncds-sdk/src/main/resources/schemas/Benzinga.avsc
=> Benzinga Schema Added

ncds-sdk/src/main/resources/schemas/NLSBSX.avsc, ncds-sdk/src/main/resources/schemas/NLSPSX.avsc
Adding schema NLSBSX and NLSPSX
=> Adding schema NLSBSX and NLSPSX

ncds-sdk/src/main/resources/schemas/NLSCTA.avsc, ncds-sdk/src/main/resources/schemas/NLSUTP.avsc
Updating Schema for NLSplus changes
=> Updating Schema for NLSplus changes

ncds-sdk/pom.xml, ncds-sdk/src/main/java/com/nasdaq/ncdsclient/consumer/NasdaqKafkaAvroConsumer.java, ncds-sdk/src/main/java/com/nasdaq/ncdsclient/internal/ReadSchemaTopic.java, ncdssdk-client/pom.xml, pom.xml
Reusing Consumer group within NCDS sdk
=> Reusing Consumer Group

README.md, ncds-sdk/pom.xml, ncds-sdk/src/main/java/com/nasdaq/ncdsclient/consumer/NasdaqKafkaAvroConsumer.java, ncdssdk-client/pom.xml, pom.xml
allows client to fix the consumer group id
=> fixed consumer group release

ncds-sdk/pom.xml, ncds-sdk/src/test/java/com/nasdaq/ncdsclient/core/controlevent/StreamInitiated.java, ncdssdk-client/pom.xml, pom.xml
1. Updated Strimzi Oauth common version to 0.8.1
2. Updated kafka version to 2.8.0
3. Fixing vulnerabilities highlighted by github scan
=> Release 0.7.x release

README.md
Adding in debug config instructions for Java SDK
=> Debug config

ncds-sdk/pom.xml, ncds-sdk/src/main/java/com/nasdaq/ncdsclient/internal/ReadSchemaTopic.java, ncdssdk-client/pom.xml, pom.xml
=> Dependency fixes
